---
title: "OPTIMA: spécifications"
author: "ISAE SUPAERO"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    css: ./../../../css/baobab_docs.css
    toc: yes
  pdf_document: default
  word_document: default
institute: ISAE SUPAERO
# geometry: margin=1.5in
---

## Glossaire

* **Maintenance** : opération d'entretien (préventive) technique nécessitant l'immobilisation de l'avion concerné. Aussi appelée "visite". Les maintenances considérées sont de quatre types. Chaque type de visite a des caractéristiques spécifiques : une durée, une périodicité, une capacité, etc.
    * Visite de sécurité (VS).
    * Visite de graissage (VG).
    * Visite intermédiaire (VI).
    * Grande visite (VX aussi appelée M).
* **Heures de vol (HDV)** : nombre d'heures de l'utilisation effective d'un avion pendant un certain temps (un mois, un an).
* **Butée calendaire (BC)** : intervalle de temps calendaire de durée maximale entre deux visites consécutives du même type. Unité : jours.
* **Butée horaire (BH)** : nombre d’heures de vol autorisées entre deux visites consécutives du même type. Unité : heures (de vol).
* **Flotte** : ensemble des avions concernés par la planification. Chaque avion a ses caractéristiques techniques et son historique des maintenances et des heures de vol effectuées.
* **Livraison** : arrivée d’un nouvel avion dans la flotte. 
* **Base aérienne** : endroit où sont réalisées les visites de la flotte. Pour chaque type de visite, le nombre d’avions est limité par une capacité de maintenance de ce type.
* **Vieillissement** : le nombre d’heures effectuées par un avion depuis son entrée en service. Pour l’instant,  les indices de fatigue ne sont pas considérés.
* **Vieillissement homogène** : l’objectif recherché est d’avoir le ratio « vieillissement/temps depuis l'entrée en service » le plus homogène possible pour les différents avions de la flotte.
* **Indices de fatigue** : indices spécifiques de différents composants de l’avion dont l’analyse peut déclencher une maintenance.
* **Mission** : une demande spécifique d'avions pendant une durée de temps donnée (quantifiée en périodes) et avec un nombre donné d'heures par période.

## Aéronefs

Chaque avion a un état défini au moment de la planification :

* **Vieillissement**.
* **Date d'entrée en service**.
* **Type**.

et pour chaque type de visite :

* **Date de la dernière visite**.
* **Nombre d'heures de vol après la dernière visite**.

Il est considéré qu'en dépassant 5000 HDV, l'avion ne peut plus être utilisé pour voler.
La flotte aura une taille de 60 avions au début de l'horizon de planification.
Le type sera utilisé pour pouvoir affecter les avions aux missions.

### Livraisons

Les livraisons de nouveaux avions se font par lot avec une moyenne annuelle. En partant d'une quantité annuelle, les avions arrivent par lot tout au long de l'année.

Par exemple, avec une moyenne de 10 avions livrés et un lot de taille 4, la distribution serait la suivante :

* Avril : 4 avions.
* Août : 4 avions.
* Décembre : 2 avions.

**Les livraisons ne font pas partie de la première version officielle (2019-12-31) du logiciel.**

## Missions / Heures de vol

Les heures de vol sont utilisées pour générer une planification initiale de maintenances. Les informations des missions sont utilisées à posteriori pour affecter les avions aux missions.

### Heures de vol

Au moment de décider le calendrier de maintenances, nous supposons une charge en heures de vol à réaliser par avion. Cette charge peut être calculée à partir de la demande annuelle par avion (200 HDV) et sera représentée comme une demande mensuelle d'heures de vol par avion.

Tout avion qui n'est pas dans une grande visite (VX ou M) est considéré comme disponible pour voler et, donc, doit être utilisé pour effectuer une quantité d'heures équivalente à sa demande mensuelle.

Le nombre d'heures de vol précis pour un avion et période donné pourra être configuré par l'utilisateur. Trois niveaux de configuration sont disponibles :

1. "Heures de vol par période" pour toute la flotte. 1 paramètre par planification.
2. Heures de vol par période pour chaque avion. 1 paramètre pour avion.
3. Heures de vol pour chaque avion et chaque période. 1 paramètre pour avion-mois: 

Exemple:

```
params.min_usage_period = 15
```

```
avions=
| avion| mois     |  min_usage_period    |
|-----------    |----|----|
| A_1  | 2019-04  |  14    |
| A_2  | 2019-04  |  14    |
| A_2  | 2019-04  |  14    |
| A_2  | 2019-04  |  14    |

```

```
heures_vol=
|avion  |   heures  | min_usage_period  |
|-----------    |----|----|             
|A_1    | 0         |   16              |
|A_10   |  0        |   16              |
|A_11   |  0        |   16              |
|A_12   |  0        |   16              |

```

| avion| mois     |  min_usage_period    |
|-----------    |----|----|
| A_1  | 2019-04  |  14    |
| A_2  | 2019-04  |  14    |
| A_2  | 2019-04  |  14    |
| A_2  | 2019-04  |  14    |

### Missions

Un ensemble de missions sont connues au long de l'horizon de planification. Chaque mission contient :

1. Un nombre d'avions à utiliser.
2. Un type d'avion à utiliser.
2. Un nombre d'heures de vol (HDV) à réaliser pour chaque avion et à chaque période (mois) de la mission.
3. Une date (période) de début et une date (période) de fin.

Si une mission donnée avait besoin d'avions de deux types différents, nous devrions séparer la mission originale en plusieurs missions indépendantes, une mission par type. Exemple : Mission $O1$ a besoin de $N$ avions de type $1$ et $M$ avions de type $2$. Nous devrons, donc, créer deux missions : la mission $O1a$ qui demande $N$ avions et qui a le type $1$; et la mission $O1b$ qui demande $M$ avions et qui a le type $2$. Les autres caractéristiques restent les mêmes.

Nous supposons que le nombre d'heures de vol à réaliser est le même pour chaque avion affecté à la mission.

Pendant l'affectation à une mission, l'avion ne peut pas faire les maintenances VX et VS.

La capacité de la base pour faire de maintenances du type 2 est réduite de façon proportionnelle à la proportion des avions qui partent en fonction de la flotte entière. Exemple : une flotte de 20 avions qui a une capacité de maintenance de 40 jours-hommes voit partir 5 avions en mission. La capacité restante dans la base sera de $40 \times (20-5)/20 = 30$ jours-hommes pendant la durée de cette mission.

Les affectations d'avions aux missions se font une fois les visites ont été déjà décidées. Concernant les heures par défaut, elles seront réduites pour les avions qui partent en mission de façon à garder le nombre d'heures de vol de l'avion qui correspond à son cycle de maintenance. Les affectations doivent être compatibles avec les visites déjà présentes. Les compatibilités à tenir compte sont les suivantes :

1. Un avion affecté à une mission doit être affecté pendant toute la durée de la mission.
1. Un avion ne peut pas voler plus de 500 h (ou la butée horaire VS / VX correspondante) en sommant toutes les heures résultantes des affectations, entre une visite VS et une visite VX (ou M) et entre deux visites du type VX. Ici, nous ne comptons pas les heures de vol par défaut de l'avion, vu que ces heures peuvent se voir réduites en fonction des heures de vol provenant des affectations aux missions.
2. Un avion ne peut pas être affecté à une mission pendant une visite de sécurité (VS) ou une grande visite (VX ou M).
3. Un avion ne peut pas être affecté à deux missions en même temps.
3. Suite à la réduction de capacité de maintenance liée à la mission, il doit rester assez de capacité pour faire les visites des avions qui restent sur place.

Exemple du point (2):
<!-- TODO -->

## Maintenances

### Caractéristiques de visites

Les maintenances sont les opérations qui récupèrent le potentiel de vol des avions. Chaque visite doit être programmée de façon à respecter la butée horaire et /ou la butée calendaire (en fonction de la visite). Pour la visite VX, elle doit respecter le plus contraignant des deux.

Chaque type de maintenance se différencie par les paramètres suivants :

* **Durée (mois)** : durée d'affectation de l'opération en périodes.
* **BC (mois)** : nombre maximal de mois entre deux visites du même type.
* **BC (tol.)** : taille de l'intervalle de tolérance (en mois) de la BC.
* **BH (HDV)** : nombre maximal d'heures de vol entre deux visites du même type.
* **BH (tol)** : taille de l'intervalle de tolérance (en heures de vol) de la BH.
* **Utilisation** : utilisation unitaire de la ressource de capacité.
* **Type** : Type de maintenance. Les visite du même type partage la même capacité.

Cependant, tout type de maintenance ne possède pas l'ensemble de ces paramètres. Pour les quatre types de maintenance considérés, voici les paramètres à prendre en compte : 

|Caractéristique|VG  |VI  |VS  |VX  |
|-----------    |----|----|----|----|
|Durée (mois)   | 1  | 1  | 1  | 4 |
|BC (mois)      |8   | 16 | -  |60  |
|BC (tol.)      |2   | 2  | -  | 4  |
|BH (HDV)       |  - | -  | 500|1000|
|BH (tol.)      | -  | -  | 100|  - |
|Utilisation    |  3 | 6  |  4 |  1 |
|Type           | 2  |2   | 2  | 1  |

La validation d'un seul critère de maintenance suffit pour immobiliser l'avion.
La visite VX (M) inclut déjà toutes les autres visites et, donc, réinitialise les BC et BH des avions pour les autres 3 visites.
Les visites de type 2 récupèrent le potentiel au début de l'opération. Pour la visite VX, le potentiel est récupéré à la fin de la visite.
Pour la VS les clients préfèrent déclencher la visite toutes les 500 - 600 HDV.

### Types de maintenances et capacités

Il existe deux types d'atelier de maintenance. Chaque maintenance ne peut être faite que dans un ces deux ateliers (celui qui corresponde au type de la maintenance). Chaque atelier a une capacité par période donnée mais elle peut changer en fonction de la période de l'année. L'utilisateur aura les moyens de configurer la capacité de maintenance en fonction de chaque période et de chaque atelier.

|Atelier        |1   | 2 |
|-----------    |----|---|
|Capacité       | 66 | 4 |

Les trois premiers types de visite (VS, VG, VI) sont faites sur chaque base aérien et donc, partagent la capacité. La quatrième visite (VX ou M) se fait sur l'atelier dédié de façon indépendant.

A chaque période, la capacité de l'atelier doit être plus grande que la somme des utilisations unitaires (voir *Utilisation* sur le tableau de maintenances) des avions en maintenance dans l'atelier. L'utilisation est décrite dans le tableau des caractéristiques des maintenances.

Exemple : imaginons une période où la capacité est égale à 40 pour la maintenance de type 2. Nous pouvons réaliser, au maximum, 10 visites VS et aucune autre visite : $10 \times 4 = 40$. Alternativement, nous pouvons faire 2 visites VG, 3 visites VI et 4 visites VS : $2 \times 3 + 3 \times 6 + 4 \times 4 = 40$.

### Regroupements de visites

Il existe la possibilité de regrouper deux ou plus de visites. Un tel regroupement permet d'économiser un jour par visite regroupée. Par exemple, si les visites `VG` et `VI` sont regroupées, leur durée totale sera de $3 + 6 - 1 = 8$ jours. Si les visites `VG`, `VI` et `VS`  sont regroupées, leur durée totale sera de $3 + 6 + 4 - 2 = 11$ jours. C'est aussi possible de faire les visites `VG` et `VS` sans faire la visite `VI`.

## Stockage

Il est possible de stocker un avion pendant un temps déterminé. L'avion stocké est immobilisé et son service est arrêté, ce qui signifie que le temps de stockage est exclu du calcul des butées calendaires.

* Le temps de stockage correspond normalement à 24 mois. Les options considérées de stockage seront les suivantes : 12 mois, 18 mois et 24 mois.
* L'avion stocké est considéré comme indisponible.
* Il n'y a pas de limite sur le nombre d'avions stockés.
* La mise en stockage d'un avion (et la sortie du stockage) prend entre 1 et 2 jours et utilise les ressources des maintenances dans la base.

**Le stockage ne fait pas partie de la première version officielle (2019-12-31) du logiciel.**

## Objectifs

L'objectif principal est de maximiser le regroupement de visites de maintenance. Un objectif secondaire vise à retarder les visites de sécurité (VS) le plus possible.

L'horizon de planification est d'entre 50 et 70 périodes mensuelles (entre 4 et 6 ans).
