# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 616)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 781, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 591, 429))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chooseFile = QtWidgets.QPushButton(self.layoutWidget)
        self.chooseFile.setDefault(False)
        self.chooseFile.setObjectName("chooseFile")
        self.horizontalLayout_2.addWidget(self.chooseFile)
        self.excel_path = QtWidgets.QLabel(self.layoutWidget)
        self.excel_path.setMinimumSize(QtCore.QSize(300, 0))
        self.excel_path.setBaseSize(QtCore.QSize(0, 0))
        self.excel_path.setText("")
        self.excel_path.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.excel_path.setObjectName("excel_path")
        self.horizontalLayout_2.addWidget(self.excel_path)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.instCheck = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instCheck.setFont(font)
        self.instCheck.setStyleSheet("QLabel { color : red; }")
        self.instCheck.setTextFormat(QtCore.Qt.AutoText)
        self.instCheck.setObjectName("instCheck")
        self.verticalLayout_2.addWidget(self.instCheck)
        self.solCheck = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.solCheck.setFont(font)
        self.solCheck.setStyleSheet("QLabel { color : red; }")
        self.solCheck.setObjectName("solCheck")
        self.verticalLayout_2.addWidget(self.solCheck)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.labe45 = QtWidgets.QLabel(self.layoutWidget)
        self.labe45.setObjectName("labe45")
        self.gridLayout.addWidget(self.labe45, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.start_date = QtWidgets.QDateEdit(self.layoutWidget)
        self.start_date.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.start_date.setCalendarPopup(True)
        self.start_date.setTimeSpec(QtCore.Qt.TimeZone)
        self.start_date.setObjectName("start_date")
        self.gridLayout.addWidget(self.start_date, 0, 1, 1, 1)
        self.end_date = QtWidgets.QDateEdit(self.layoutWidget)
        self.end_date.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.end_date.setCalendarPopup(True)
        self.end_date.setObjectName("end_date")
        self.gridLayout.addWidget(self.end_date, 1, 1, 1, 1)
        self.max_time = QtWidgets.QLineEdit(self.layoutWidget)
        self.max_time.setEnabled(True)
        self.max_time.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.max_time.setMaxLength(4)
        self.max_time.setObjectName("max_time")
        self.gridLayout.addWidget(self.max_time, 2, 1, 1, 1)
        self.label2345 = QtWidgets.QLabel(self.layoutWidget)
        self.label2345.setObjectName("label2345")
        self.gridLayout.addWidget(self.label2345, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.generateSolution = QtWidgets.QPushButton(self.layoutWidget)
        self.generateSolution.setDefault(False)
        self.generateSolution.setObjectName("generateSolution")
        self.horizontalLayout.addWidget(self.generateSolution)
        self.checkSolution = QtWidgets.QPushButton(self.layoutWidget)
        self.checkSolution.setObjectName("checkSolution")
        self.horizontalLayout.addWidget(self.checkSolution)
        self.exportSolution = QtWidgets.QPushButton(self.layoutWidget)
        self.exportSolution.setDefault(False)
        self.exportSolution.setObjectName("exportSolution")
        self.horizontalLayout.addWidget(self.exportSolution)
        self.exportSolution_to = QtWidgets.QPushButton(self.layoutWidget)
        self.exportSolution_to.setDefault(False)
        self.exportSolution_to.setObjectName("exportSolution_to")
        self.horizontalLayout.addWidget(self.exportSolution_to)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.solution_log = QtWidgets.QTextBrowser(self.layoutWidget)
        self.solution_log.setObjectName("solution_log")
        self.verticalLayout.addWidget(self.solution_log)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseFile.setText(_translate("MainWindow", "Browse"))
        self.instCheck.setText(_translate("MainWindow", "no instance loaded"))
        self.solCheck.setText(_translate("MainWindow", "no solution loaded"))
        self.labe45.setText(_translate("MainWindow", "End date"))
        self.label_3.setText(_translate("MainWindow", "Max time                                                                                                         "))
        self.start_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM"))
        self.end_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM"))
        self.label2345.setText(_translate("MainWindow", "Start date"))
        self.generateSolution.setText(_translate("MainWindow", "generate solution"))
        self.checkSolution.setText(_translate("MainWindow", "check solution"))
        self.exportSolution.setText(_translate("MainWindow", "export solution"))
        self.exportSolution_to.setText(_translate("MainWindow", "export solution to"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Page"))

